# Generated by Django 4.1.6 on 2023-02-07 17:11

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Entry',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('full_text', models.TextField()),
                ('is_resolved', models.BooleanField(default=False)),
                ('channel', models.CharField(max_length=255)),
                ('extra_parameters', models.TextField()),
            ],
            options={
                'ordering': ['-id'],
            },
        ),
    ]
