# Generated by Django 4.1.6 on 2023-02-07 17:16

# Django Stuff
from django.db import models, migrations


class Migration(migrations.Migration):
    dependencies = [
        ("feeds", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="entry",
            name="channel",
            field=models.CharField(
                choices=[
                    ("twitter", "twitter"),
                    ("telegram", "telegram"),
                    ("twitch", "twitch"),
                    ("discord", "discord"),
                ],
                max_length=255,
            ),
        ),
    ]
