# Generated by Django 4.1.6 on 2023-02-07 17:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('feeds', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='entry',
            name='channel',
            field=models.CharField(choices=[('twitter', 'twitter'), ('telegram', 'telegram'), ('twitch', 'twitch'), ('discord', 'discord')], max_length=255),
        ),
    ]
