# Generated by Django 4.1.6 on 2023-02-08 17:22

# Django Stuff
import django.db.models.deletion
import django.contrib.postgres.fields
from django.db import models, migrations


class Migration(migrations.Migration):
    dependencies = [
        ("feeds", "0005_location"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="location",
            options={"ordering": ["-id"]},
        ),
        migrations.AddField(
            model_name="entry",
            name="is_geolocated",
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name="entry",
            name="location",
            field=django.contrib.postgres.fields.ArrayField(
                base_field=models.CharField(max_length=255), null=True, size=None
            ),
        ),
        migrations.AlterField(
            model_name="entry",
            name="channel",
            field=models.CharField(
                choices=[
                    ("twitter", "twitter"),
                    ("telegram", "telegram"),
                    ("twitch", "twitch"),
                    ("discord", "discord"),
                    ("depremyardim", "depremyardim"),
                ],
                max_length=255,
            ),
        ),
        migrations.AlterField(
            model_name="location",
            name="entry",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="entries",
                related_query_name="entry",
                to="feeds.entry",
            ),
        ),
    ]
