# Generated by Django 4.1.6 on 2023-02-08 17:35

# Django Stuff
import django.contrib.postgres.fields
from django.db import models, migrations


class Migration(migrations.Migration):
    dependencies = [
        ("feeds", "0006_alter_location_options_entry_is_geolocated_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="entry",
            name="location",
            field=django.contrib.postgres.fields.ArrayField(
                base_field=models.FloatField(default=0.0), null=True, size=None
            ),
        ),
    ]
