# Generated by Django 4.1.6 on 2023-02-08 17:46

# Django Stuff
from django.db import models, migrations


class Migration(migrations.Migration):
    dependencies = [
        ("feeds", "0007_alter_entry_location"),
    ]

    operations = [
        migrations.AlterField(
            model_name="entry",
            name="channel",
            field=models.CharField(
                choices=[
                    ("twitter", "twitter"),
                    ("telegram", "telegram"),
                    ("twitch", "twitch"),
                    ("discord", "discord"),
                    ("depremyardim", "depremyardim"),
                    ("manual", "manual"),
                ],
                max_length=255,
            ),
        ),
    ]
