# Generated by Django 4.1.6 on 2023-02-08 10:03

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('instagram', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='InstagramPostToFollow',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('url', models.URLField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
        ),
        migrations.AlterField(
            model_name='instagrampost',
            name='post_id',
            field=models.CharField(max_length=255, unique=True),
        ),
        migrations.CreateModel(
            name='InstagramComment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('user_id', models.CharField(max_length=255)),
                ('screen_name', models.CharField(max_length=512)),
                ('name', models.CharField(max_length=255)),
                ('post_id', models.CharField(max_length=255)),
                ('comment_id', models.CharField(max_length=255)),
                ('created_at', models.DateTimeField(blank=True, null=True)),
                ('full_text', models.TextField()),
                ('is_active', models.BooleanField(default=True)),
                ('followed_post', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='instagram.instagramposttofollow')),
            ],
            options={
                'ordering': ['-id'],
            },
        ),
    ]