# Generated by Django 4.1.6 on 2023-02-06 20:36

# Django Stuff
from django.db import models, migrations


class Migration(migrations.Migration):
    dependencies = [
        ("tweets", "0004_address_city_address_distinct_address_name_surname_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="address",
            name="tel",
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
