# Generated by Django 4.1.6 on 2023-02-06 20:52

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('tweets', '0005_address_tel'),
    ]

    operations = [
        migrations.AddField(
            model_name='address',
            name='is_resolved',
            field=models.BooleanField(default=False),
        ),
        migrations.CreateModel(
            name='Location',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('latitude', models.FloatField(default=0.0)),
                ('longitude', models.FloatField(default=0.0)),
                ('northeast_lat', models.FloatField(default=0.0)),
                ('northeast_lng', models.FloatField(default=0.0)),
                ('southwest_lat', models.FloatField(default=0.0)),
                ('southwest_lng', models.FloatField(default=0.0)),
                ('is_approved', models.BooleanField(default=False)),
                ('address', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='tweets.address')),
            ],
        ),
    ]
