# Generated by Django 4.1.6 on 2023-02-06 20:55

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('tweets', '0006_address_is_resolved_location'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='location',
            options={'ordering': ['-id']},
        ),
    ]
