# Generated by Django 4.1.6 on 2023-02-06 21:00

# Django Stuff
from django.db import models, migrations


class Migration(migrations.Migration):
    dependencies = [
        ("tweets", "0007_alter_location_options"),
    ]

    operations = [
        migrations.AddField(
            model_name="location",
            name="formatted_address",
            field=models.TextField(blank=True, null=True),
        ),
    ]
