# Generated by Django 4.1.6 on 2023-02-07 14:55

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('instagram', '0001_initial'),
        ('tweets', '0008_location_formatted_address'),
    ]

    operations = [
        migrations.AddField(
            model_name='address',
            name='instagram_post',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='instagram.instagrampost'),
        ),
        migrations.AlterField(
            model_name='address',
            name='tweet',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='tweets.tweet'),
        ),
    ]