# Generated by Django 4.1.6 on 2023-02-07 18:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tweets', '0008_location_formatted_address'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tweet',
            name='tweet_id',
            field=models.CharField(max_length=255, unique=True),
        ),
    ]
