# Generated by Django 4.1.6 on 2023-02-08 10:03

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('instagram', '0002_instagramposttofollow_alter_instagrampost_post_id_and_more'),
        ('tweets', '0009_address_instagram_post_alter_address_tweet'),
    ]

    operations = [
        migrations.AddField(
            model_name='address',
            name='instagram_comment',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='instagram.instagramcomment'),
        ),
    ]